### ISSUE TITLE
Does not work on Firefox < 45

### ISSUE THREAD

**Issue by moimael** [maximus8891/flux-queue-dispatcher#1]
Hi,

Using your package on npm, I get a `SyntaxError: class is a reserved identifier`.

It makes sense since Firefox does not support ES6 class until release 45. Any plan to transpile that with babel to more traditional es5 ?

Thanks !

**Comment by max-ch9i** [comment]
Hi moimael,
Thank you for checking it out. I would expect the package to be used in conjunction with ES6 components, which are transpiled altogether, but I certainly can look into making an ES5 compatible variant.

**Comment by max-ch9i** [comment]
FB Flux doesn't ship with ES5 source files. Please, use a transpiler on a project level to make the dispatcher compatible.
